name: TFT MLOps CI

on:
  push:
    branches: [main]

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: airflow
          POSTGRES_PASSWORD: airflow
          POSTGRES_DB: airflow
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install apache-airflow==2.9.0

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src/ --max-line-length=100

    - name: Run tests
      run: |
        if [ -d "tests" ]; then
          pytest tests/
        else
          echo "No tests/ folder found. Skipping unit tests."
        fi

    - name: Validate Airflow DAGs
      run: |
        airflow db init
        airflow dags list